### ISSUE TITLE
[bug] Noun Verbed can’t fit overlong text

### ISSUE THREAD

**Issue by lucaswerkmeister** [olivvybee/imagenerator#85]
**Describe the bug**
The [Noun Verbed generator](https://imagenerator.net/noun-verbed) can cut off the text at the sides if it’s too long.

**How it happened**
1. go to https://imagenerator.net/noun-verbed
2. pick a 16:9 image, e.g. [this black canvas](https://github.com/olivvybee/imagenerator/assets/2346599/08f50b45-6c22-4a17-a10f-80df3afd875b)
3. enter the text “productivity achieved”

**Expected behavior**
The text fits on the image. If it’s hard to pick the font size automatically, a slider for it would be nice (to complement the existing text position slider).

**Screenshots**
![image](https://github.com/olivvybee/imagenerator/assets/2346599/6875579d-44a2-462d-990e-38c806fd86bd)

**Your device information**
 - PC
 - Firefox

**Comment by lucaswerkmeister** [comment]
Now I’m not seeing any text at all :(

![image](https://github.com/olivvybee/imagenerator/assets/2346599/4f9a04ae-d805-4f3f-a587-70ba5db1f726)
https://github.com/olivvybee/imagenerator/assets/2346599/6a970a6f-bf87-4d88-8bee-4a7c227799ad

Firefox reports three errors in the console, not sure if they’re related:
```
downloadable font: maxp: Bad maxZones: 0 (font-family: "Atkinson Hyperlegible" style:normal weight:400 stretch:100 src index:1) source: https://imagenerator.net/fonts/Atkinson-HyperLegible-Regular.woff2
downloadable font: kern: Kerning pairs are not sorted (font-family: "Optimus Princeps" style:normal weight:400 stretch:100 src index:1) source: https://imagenerator.net/fonts/OptimusPrincepsSemiBold.woff2
downloadable font: Table discarded (font-family: "Optimus Princeps" style:normal weight:400 stretch:100 src index:1) source: https://imagenerator.net/fonts/OptimusPrincepsSemiBold.woff2 
```

Chrome also doesn’t show any text and puts different errors in the console:
```
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://imagenerator.net/fonts/fredoka-one-v12-latin-regular.woff2
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://imagenerator.net/fonts/Atkinson-HyperLegible-Regular.woff2
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://imagenerator.net/fonts/OptimusPrincepsSemiBold.woff2
```

**Comment by olivvybee** [comment]
Hmm it seems like the browsers are trying to fall back to another font because the actual font hasn't loaded in time, but obviously there isn't really a fallback that makes sense so they're just rendering nothing :/ there might be something I can do to force it to wait for the fonts to load

I think this might be a total coincidence that it happened now tbh, there's nothing in the change I made that affects how the fonts are actually loaded 😅

**Comment by lucaswerkmeister** [comment]
Hm, you’re right, now it’s working for me again. (But I could swear I had tried a reload already earlier…)

**Comment by olivvybee** [comment]
I played around in chrome to reproduce the behaviour and I *think* maybe you happened to load the page while it was doing another deploy so the fonts didn't load that one time, because even when I saw the `Slow network is detected` error, it had still loaded the font anyway by the time I typed into the generator

**Comment by lucaswerkmeister** [comment]
Could be, yeah.

Anyway, if it’s working I’m happy for this to be closed again. And thanks for the speedy fix :)
